<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPTfjQ45\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPTfjQ45/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPTfjQ45.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPTfjQ45\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPTfjQ45\App_KernelDevDebugContainer([
    'container.build_hash' => 'PTfjQ45',
    'container.build_id' => 'fc39d73e',
    'container.build_time' => 1692663778,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPTfjQ45');
